apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-app-deployment
spec:
  replicas: 2 # This is probably your 'line 6'. Note the indentation.
  selector:
    matchLabels:
      app: ticket-app
  template:
    metadata:
      labels:
        app: ticket-app
    spec:
      containers:
        - name: ticket-app
          # This line will be replaced by your pipeline
          image: YOUR_DOCKERHUB_USERNAME/ticket-app:latest
          ports:
            - containerPort: 5000
